name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME  }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}      

jobs:
    unit-testing:
        name: Unit Testing
        runs-on: ubuntu-latest
        steps:

        - name: Checkout Repository
          uses: actions/checkout@v7

        - name: Setup NodeJS Version
          uses: actions/setup-node@v3
          with:
            node-version: 20
    
        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          run: npm test
          
        - name: Archive Test Result
          uses: actions/upload-artifact@v7
          with:
            name: Mocha-Test-Result
            path: test-results.xml
            retention-days: 5


    code-coverage:
      name: Code Coverage
      runs-on: ubuntu-latest
      steps:

        - name: Checkout Repository
          uses: actions/checkout@v7

        - name: Setup NodeJS Version
          uses: actions/setup-node@v3
          with:
            node-version: 20

        - name: Install Dependencies
          run: npm install

        - name: Generate Coverage Report
          run: npm run coverage
          id: generate-report

          # continue-on-error: true

          # By enabling continue-on-error on the coverage step, your workflow still uploads the coverage report even if the threshold isn’t met.

        - name: Archive Coverage Report
          
          # if: failure() && steps.generate-report == 'failure' 
          # This runs the archive step when the testing step fails:

          if: always()
          # If you want the test results available on both success and failure, use always():
          
          uses: actions/upload-artifact@v7
          with:
            name: Code-Coverage-Result
            path: coverage
            retention-days: 5
